import type { ManagedFile } from "./file.types";

export const managedFiles: ManagedFile[] = [
  {
    fileId: "FILE-2026-0001",
    studentId: "STU-000128",
    studentName: "Jairus Jin Rong",
    studentNumber: "AGA-STU-000128",
    enrolmentId: "ENR-2026-0001",
    module: "Invoice PDF",
    status: "Uploaded",
    fileName: "INV-2026-0018 - Jairus Jin Rong.pdf",
    mimeType: "application/pdf",
    driveFileId: "DRIVE-INVOICE-0001",
    driveUrl: "https://drive.google.com/file/d/example-invoice-1/view",
    folderId: "FOLDER-INVOICES",
    uploadedAt: "2026-07-31T09:12:00.000Z",
    uploadedBy: "Jairus Orolaza",
    notes: "Invoice exported from finance system."
  },
  {
    fileId: "FILE-2026-0002",
    studentId: "STU-000128",
    studentName: "Jairus Jin Rong",
    studentNumber: "AGA-STU-000128",
    enrolmentId: "ENR-2026-0001",
    module: "Training Record",
    status: "Uploaded",
    fileName: "TRN-2026-0002 - UATO Theory Assessment.pdf",
    mimeType: "application/pdf",
    driveFileId: "DRIVE-TRAINING-0002",
    driveUrl: "https://drive.google.com/file/d/example-training-2/view",
    folderId: "FOLDER-TRAINING-RECORDS",
    uploadedAt: "2026-07-31T09:18:00.000Z",
    uploadedBy: "Jairus Orolaza",
    notes: "Assessment record PDF."
  },
  {
    fileId: "FILE-2026-0003",
    studentId: "STU-000130",
    studentName: "Marcus Lee",
    studentNumber: "AGA-STU-000130",
    enrolmentId: "ENR-2026-0003",
    module: "Certificate",
    status: "Uploaded",
    fileName: "CERT-2026-0002 - Marcus Lee.pdf",
    mimeType: "application/pdf",
    driveFileId: "DRIVE-CERT-0002",
    driveUrl: "https://drive.google.com/file/d/example-cert-2/view",
    folderId: "FOLDER-CERTIFICATES",
    uploadedAt: "2026-07-29T11:20:00.000Z",
    uploadedBy: "System",
    notes: "Generated certificate PDF."
  },
  {
    fileId: "FILE-2026-0004",
    studentId: "STU-000129",
    studentName: "Amelia Tan",
    studentNumber: "AGA-STU-000129",
    enrolmentId: "ENR-2026-0002",
    module: "TEA",
    status: "Missing",
    fileName: "TEA - Amelia Tan.pdf",
    mimeType: "application/pdf",
    driveFileId: "",
    driveUrl: "",
    folderId: "FOLDER-TEA",
    uploadedAt: "2026-07-30T06:45:00.000Z",
    uploadedBy: "Jairus Orolaza",
    notes: "Awaiting signed Training Enrolment Agreement."
  },
  {
    fileId: "FILE-2026-0005",
    studentId: "STU-000131",
    studentName: "Sofia Reyes",
    studentNumber: "AGA-STU-000131",
    enrolmentId: "ENR-2026-0004",
    module: "Registration Form",
    status: "Needs Replacement",
    fileName: "Registration Form - Sofia Reyes.pdf",
    mimeType: "application/pdf",
    driveFileId: "DRIVE-REG-0005",
    driveUrl: "https://drive.google.com/file/d/example-registration-5/view",
    folderId: "FOLDER-REGISTRATION-FORMS",
    uploadedAt: "2026-07-28T08:05:00.000Z",
    uploadedBy: "Jairus Orolaza",
    notes: "Identification page is outdated."
  }
];
