import type { TrainingRecord } from "./training-record.types";

export const trainingRecords: TrainingRecord[] = [
  {
    recordId: "TRN-2026-0001",
    studentId: "STU-000128",
    studentName: "Jairus Jin Rong",
    studentNumber: "AGA-STU-000128",
    enrolmentId: "ENR-2026-0001",
    courseCode: "UATO",
    courseName: "UATO Remote Pilot Course",
    recordType: "Theory Lesson",
    recordDate: "2026-07-05",
    moduleName: "Airspace Rules and Safety",
    result: "Completed",
    trainerName: "Rachel Lim",
    durationMinutes: 120,
    remarks: "Completed classroom theory session.",
    pdfFileId: "PDF-TRN-0001",
    pdfUrl: "https://drive.google.com/file/d/example-1/view",
    updatedAt: "2026-07-31T09:12:00.000Z"
  },
  {
    recordId: "TRN-2026-0002",
    studentId: "STU-000128",
    studentName: "Jairus Jin Rong",
    studentNumber: "AGA-STU-000128",
    enrolmentId: "ENR-2026-0001",
    courseCode: "UATO",
    courseName: "UATO Remote Pilot Course",
    recordType: "Assessment",
    recordDate: "2026-07-18",
    moduleName: "UATO Theory Assessment",
    score: 88,
    result: "Passed",
    trainerName: "Rachel Lim",
    durationMinutes: 90,
    remarks: "Passed theory assessment. Eligible for practical review.",
    pdfFileId: "PDF-TRN-0002",
    pdfUrl: "https://drive.google.com/file/d/example-2/view",
    updatedAt: "2026-07-31T09:18:00.000Z"
  },
  {
    recordId: "TRN-2026-0003",
    studentId: "STU-000129",
    studentName: "Amelia Tan",
    studentNumber: "AGA-STU-000129",
    enrolmentId: "ENR-2026-0002",
    courseCode: "CAAS-PA",
    courseName: "CAAS Practical Assessment",
    recordType: "Practical Lesson",
    recordDate: "2026-08-12",
    moduleName: "Pre-flight Procedures",
    result: "Pending",
    trainerName: "Jonathan Wee",
    durationMinutes: 75,
    remarks: "Scheduled after enrolment approval.",
    updatedAt: "2026-07-30T06:45:00.000Z"
  },
  {
    recordId: "TRN-2026-0004",
    studentId: "STU-000130",
    studentName: "Marcus Lee",
    studentNumber: "AGA-STU-000130",
    enrolmentId: "ENR-2026-0003",
    courseCode: "FIC",
    courseName: "Flight Instructor Check",
    recordType: "Completion",
    recordDate: "2026-06-18",
    moduleName: "Instructor Competency Review",
    score: 94,
    result: "Completed",
    trainerName: "Priya Nair",
    durationMinutes: 180,
    remarks: "Completed with strong practical performance.",
    pdfFileId: "PDF-TRN-0004",
    pdfUrl: "https://drive.google.com/file/d/example-4/view",
    updatedAt: "2026-07-29T11:20:00.000Z"
  },
  {
    recordId: "TRN-2026-0005",
    studentId: "STU-000131",
    studentName: "Sofia Reyes",
    studentNumber: "AGA-STU-000131",
    enrolmentId: "ENR-2026-0004",
    courseCode: "SIM-RF",
    courseName: "Simulator Refresher",
    recordType: "Remedial",
    recordDate: "2026-07-22",
    moduleName: "Emergency Response Recovery",
    score: 62,
    result: "Requires Follow Up",
    trainerName: "Darren Chua",
    durationMinutes: 105,
    remarks: "Needs additional practice before final assessment.",
    pdfFileId: "PDF-TRN-0005",
    pdfUrl: "https://drive.google.com/file/d/example-5/view",
    updatedAt: "2026-07-28T08:05:00.000Z"
  }
];
